Provide detailed log out for rejected battery configuration requests
LibreSolar/charge-controller-firmware pull request #127
Opened 2022-01-17 20:58 UTC by hogthrob

It also gets rid of the duplication of code between the debug output
and the actual return value calculation by folding both into the same
loop.

Did this because it was quite hard to figure out what exactly caused rejection of my config changes.
It would be even better if this would be send back somehow on the thingset channel, 
but this is better than nothing.

2022-01-17 21:23 UTC, hogthrob commented
Don't know why the PR doesn't build, did not do anything with the can module, does compile perfectly in my build systems which is the recommended docker setup for Zephyr OS development.

2022-01-19 17:12 UTC, hogthrob commented
Ok,
the build problem is caused by this change in the latest development version of ZephyrOS: https://github.com/zephyrproject-rtos/zephyr/commit/b1b77c177404b53537a284b1dc1606d1fc8da8be

So it is a change between the latest release (uint32_t) to int in the development branch. Obviously we use the development branch for building the PR. As it has nothing to do with my PR, I am not touching this problem.

2022-01-19 17:36 UTC, martinjaeger commented
Thanks for the PR and the investigation of the CI build error. We are actually **not** using the development branch of Zephyr, but the v2.7-branch, which is the latest long-term stable release. It's defined via `west.yml`, see here:
https://github.com/LibreSolar/charge-controller-firmware/blob/a56b0d0e8046fcb911dd2a21015845509d13565a/west.yml#L14

Normally, only bug-fixes are backported to previous release branches. I'll double-check if that particular commit was backported, but I'm a bit busy with other stuff ATM. Will also come back to your PR ASAP.

2022-01-19 17:41 UTC, martinjaeger commented
Ok, it was backported and I even approved it: https://github.com/zephyrproject-rtos/zephyr/pull/41531

Wasn't aware that it would break existing firmware. So I'll provide a fix here.

2022-01-19 18:01 UTC, martinjaeger requested changes
I've fixed the CAN issue in main branch, after a rebase to main CI should pass.

The suggestion looks good. And I agree it would be very helpful to finally add the error message to the ThingSet response.

May I ask you to stick with the coding style of the rest of the code base as described [here](https://github.com/LibreSolar/coding-style)? After the style fixes it should be good to go in. Thanks.

2022-01-19 18:03 UTC, martinjaeger requested changes

2022-01-19 18:03 UTC, martinjaeger commented on app/src/bat_charger.cpp
> +    {
```suggestion
    for (auto cond: conditions) {
```

2022-01-19 18:03 UTC, martinjaeger commented on app/src/bat_charger.cpp
> +	{ .func = [bat_conf]() { return bat_conf->load_reconnect_voltage > (bat_conf->load_disconnect_voltage + 0.4); }, .text = "Load Reconnect Voltage must be higher than Load Disconnect Voltage + 0.4" },
Lines too long (should be <100 chars) and tabs are used instead of 4 spaces for indentation.

2022-01-19 21:04 UTC, hogthrob commented
Thanks! Will try to follow your hints.

BTW, it would be extremely cool to have a .clang-format definition for the coding style. That would make following the style for committers (and you much easier), especially if in .vscode format on save is enabled. Or am I missing something here, how I could format this code automatically?

2022-01-19 21:17 UTC, martinjaeger commented
> BTW, it would be extremely cool to have a .clang-format definition for the coding style. That would make following the style for committers (and you much easier), especially if in .vscode format on save is enabled. Or am I missing something here, how I could format this code automatically?

That's a good hint. Never thought about it. I've done some Rust programming recently and really love that you can just run `cargo fmt` and everything looks nice and homogeneous. I'll check out what a clang format can do for us here :)

> For a "part-time" committer in multiple projects it is really difficult to follow all the different styles. At the same time I absolutely understand the need to follow a single style in a project.

Fully understood. And there are sooo many different styles for C/C++.

2022-01-23 10:53 UTC, hogthrob commented
BTW, the coding style link in the CONTRIBUTING.md is pointing to nowhere. Did not update this as it would break the atomic commit rule ;-)

Anyways, what you see in the function is the result of using the following formatting rules in `.clang-format` (place file in top level dir)
```yaml
BasedOnStyle: LLVM
UseTab: Never
IndentWidth: 4
TabWidth: 4
BreakBeforeBraces: Linux
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 100
AccessModifierOffset: -4
NamespaceIndentation: All
FixNamespaceComments: false 
```

Not sure, if this exactly matches the intended style, but by placing this file in the main repo, VS Code C++ formatting would be following this whenever used. I recommend to use the formatOnSave option for the workspace, then it gets formatted when stuff is saved and nobody can forget this (as long as VS Code is being used...). But even without the forced formatting this would be a great help.

2022-01-25 11:51 UTC, martinjaeger approved these changes

2022-01-25 11:56 UTC, merged